"""empty message

Revision ID: ce7500ae351a
Revises: 1b3ecac652be
Create Date: 2018-12-18 20:18:35.892824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7500ae351a'
down_revision = '1b3ecac652be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lakers',
    sa.Column('tile', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lakers')
    # ### end Alembic commands ###
